import { useState } from "react";
import { ArrowUpRight, X } from "lucide-react";
import bovonto from "@/assets/Bovonto.webp"; import campa from "@/assets/Campa-flavour-gemini-1.jpg"; import ruby from "@/assets/Ruby-main-gemini.jpg"; import vibro from "@/assets/vibro-gemini.png"; import bingo from "@/assets/product-bingo-yumitos.webp"; import podaran from "@/assets/product-podaran.jpg"; import mani from "@/assets/product-manimark-peanuts.jpg"; import tea from "@/assets/tea-gemini.jpg"; import coffee from "@/assets/l1.jpeg"; import ponvandu from "@/assets/product-ponvandu.jpg"; import power from "@/assets/product-power-soaps.png";
type Item = { name:string; type:string; src:string; size?:string };
const items: Item[] = [
  { name:"Bovonto Range", type:"ICONIC SOFT DRINKS", src:bovonto, size:"wide" }, { name:"Campa Series", type:"BEVERAGES", src:campa }, { name:"Ruby Badam", type:"SUPER STOCKIEST", src:ruby }, { name:"Vibro Drink", type:"BEVERAGES", src:vibro },
  { name:"Bingo & Snacks", type:"SNACKS", src:bingo }, { name:"Podaran", type:"SNACKS", src:podaran }, { name:"Mani Mark", type:"PEANUTS & SWEETS", src:mani }, { name:"Chakra Gold", type:"PREMIUM TEA", src:tea }, { name:"Levista", type:"COFFEE", src:coffee }, { name:"Ponvandu", type:"HOME CARE", src:ponvandu }, { name:"Power", type:"HOUSEHOLD ESSENTIALS", src:power }
];
export default function ProductCatalog(){ const [active,setActive]=useState<Item|null>(null); return <section id="products" className="products-new"><header><span className="section-label">02 / THE PORTFOLIO</span><h2>Not a catalogue.<br /><i>A considered shelf.</i></h2><p>Discover the brands and everyday products that keep local retailers supplied, organised and ready to sell.</p></header><div className="product-mosaic">{items.map((item,i)=><button className={`product-tile tile-${i} ${item.size ?? ""}`} key={item.name} onClick={()=>setActive(item)}><span className="tile-index">0{i+1}</span><img src={item.src} alt={item.name}/><span className="tile-copy"><small>{item.type}</small><strong>{item.name}</strong><ArrowUpRight size={19}/></span></button>)}</div>{active&&<div className="product-lightbox" onClick={()=>setActive(null)}><button onClick={()=>setActive(null)}><X/></button><img src={active.src} alt={active.name}/><p>{active.name}</p></div>}</section>; }
